.github/CODEOWNERS
=> ci: set codeowners

go/node/deployment/v1beta2/events_test.go, go/node/deployment/v1beta3/events_test.go, go/node/market/v1beta1/events_test.go, go/node/market/v1beta3/events_test.go, go/node/provider/v1beta1/events_test.go, go/sdkutil/config.go
=> refactor(sdkutil): seal sdk config inside init()

go/node/deployment/v1beta2/migrate/v1beta1.go, go/node/market/v1beta2/migrate/v1beta1.go
=> fix: backport legacy migrations for history

go/node/deployment/v1beta3/migrate/v1beta2.go, go/node/types/v1beta3/migrate/v1beta2.go
=> fix(migrations): add market order migration for v1beta3

make/setup-cache.mk, script/protocgen-legacy.sh
=> fix(proto-gen): unpack missing protobuf files

go/manifest/v2beta2/manifest_test.go, go/node/deployment/v1beta3/deployment_validation_test.go, go/node/deployment/v1beta3/resource_list_validation.go, go/node/types/v1beta3/resource.go, go/testutil/v1beta3/base.go
=> fix: ensure GPU resource is always present

go.mod, go.sum
=> chore: bump cosmos-sdk v0.45.16

.github/workflows/release.yaml
=> ci(release): remove non-existing dependency

go/node/deployment/v1beta3/groupspec.go
=> fix(groupspec): check for GPU capabilities matching provider attributes

go/node/deployment/v1beta3/resource_list_validation.go
fix use of invalid config param for GPU validation
=> fix(resourceList): validate GPU only if amount > 0

go/node/deployment/v1beta3/resource_list_validation.go
=> fix: validate attributes for each resource

make/test.mk
=> test: use variables to allow filtering packages in which to run tests

.envrc, .gitignore
=> build(direnv): include dev.env if exists

go/manifest/v2beta2/manifest.go
=> feat(manifest): implement Version function

go/node/client/v1beta2/tx.go
derive parent tx factory to preserve parameters send via cli
=> fix(go/client): gas calculation for tx broadcast

.github/workflows/release.yaml
This PR is an example for the [referenced issue](https://github.com/akash-network/support/issues/206). It's not intended to be merged at this point until there's an agreement with the team made.
=> refactor(cdci): improves workflows code style (#206)

ts/src/patch/index.akash.deployment.v1beta3.ts, ts/src/patch/index.akash.market.v1beta4.ts
refs akash-network/support#184
=> feat(ts): add required market exports

ts/esbuild.config.mjs, ts/package-lock.json, ts/package.json, ts/script/protoc-gen-sdk-object.ts, ts/src/client/createClientFactory.ts, ts/src/client/createServiceClient.spec.ts, ts/src/client/createServiceClient.ts, ts/src/generated/createCosmosSDK.ts, ts/src/generated/createNodeSDK.ts, ts/src/generated/createProviderSDK.ts, ts/src/transport/grpc/createGrpcTransport.ts, ts/src/transport/types.ts, ts/test/functional/__snapshots__/protoc-gen-sdk-object.spec.ts.snap
To make it possible to specify custom type for options in tx methods
adds support for custom sdk client options
=> refactor: adds support for custom sdk client options

go/util/jwt/es256k.go, go/util/jwt/jwt.go, go/util/jwt/jwt_test.go, go/util/tls/verify.go, specs/jwt-schema.json, testdata/jwt/cases_es256k.json, testdata/jwt/cases_jwt.json.tmpl
refs akash-network/aep#37
refs akash-network/support#299
=> refactor(jwt): implement granual access per deployment at provider level

go/provider/client/client.go, go/provider/client/client_shell.go, go/provider/client/types.go
refs akash-network/support#320
=> feat(provider/client): export client helpers

go/provider/client/client.go
refs akash-network/support#320
=> fix(provider/client): add missing nbf field for token generator

go/provider/client/client.go
[Use a clear, concise title that reflects the change]
[Explain what this PR does in 2-3 sentences. Include context about the feature or problem being solved]
- Closes #ISSUE_NUMBER
- References #ISSUE_NUMBER
[Include any additional context, architectural decisions, or specific areas to focus on]
=> fix(go/provider/client): backport authz order

go/provider/client/client.go
[Use a clear, concise title that reflects the change]
[Explain what this PR does in 2-3 sentences. Include context about the feature or problem being solved]
- Closes #ISSUE_NUMBER
- References #ISSUE_NUMBER
[Include any additional context, architectural decisions, or specific areas to focus on]
=> fix(provider): set custom verifyPeerCertificate on mtls only
